@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor SM_TeamMember as actor
participant ":createTaskOutsideUserStoryUI" as UI
participant ":createTaskOutsideUserStoryController" as Ctrl
participant "proj:Project" as proj
participant "sprintList:SprintList" as sList
participant ":SprintMapper" as sMapper
participant "sprintDTO: SprintDTO" as sDTO


actor -> UI: Ask for current sprint
activate UI

UI -> Ctrl: getCurrentSprint()
activate Ctrl

Ctrl -> proj: getSprintList()
activate proj

proj -> Ctrl: sprintList
deactivate proj

Ctrl -> sList: getCurrentSprint()
activate sList

sList --> Ctrl: currentSprint
deactivate sList

Ctrl -> sMapper:toDTO(currentSprint)
activate sMapper

sMapper -> sDTO**: create()

sMapper --> Ctrl: sprintDTO
deactivate sMapper

Ctrl --> UI: sprintDTO
deactivate Ctrl

UI --> actor: sprintDTO
deactivate UI



@enduml