@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor SM_TeamMember as actor
participant ":createTaskOutsideUserStoryUI" as UI
participant ":createTaskOutsideUserStoryController" as Ctrl
participant "pStore:ProjectStore" as pStore
participant "proj:Project" as proj
participant ":ProjectMapper" as projMapper
participant "projDTO: ProjectDTO" as projDTO


actor -> UI: Choose a project
activate UI

UI -> Ctrl: getProject(projCode)
activate Ctrl

Ctrl -> pStore: getProjectByCode(projCode)
activate pStore

pStore -> proj: hasCode(projCode)
activate proj

proj --> pStore: true
deactivate proj

pStore --> Ctrl: proj
deactivate pStore

Ctrl -> projMapper: toDTO(proj)
activate projMapper

projMapper -> projDTO**: create()

projMapper --> Ctrl: projDTO
deactivate projMapper

Ctrl --> UI: projDTO
deactivate Ctrl

UI --> actor: projDTO
deactivate UI


@enduml