@startuml
'https://plantuml.com/class-diagram

title US030 - As a Team Member, i want to view the Scrum Board of a current sprint.

autoactivate on
autonumber

actor "Team Member" as TeamMember

participant ": System " as System

activate TeamMember

TeamMember -> System: Request Scrum Board
System --> TeamMember: Scrum Board Response


@enduml

