@startuml
'https://plantuml.com/sequence-diagram

title US018 - As PO/SM/TeamMember, I want to consult the Product Backlog, i. e. to get the list of user stories sorted by priority

autoactivate on
autonumber

actor "PO/SM/TeamMember" as User
participant ": ProductBacklogSortUI" as System
participant ": ProductBacklogSortController" as Ctrl
participant ": Company" as C1
participant ": ProjectsMapper" as C2.1.0
participant "projStore : ProjectStore" as C2
participant "projectListByUser : List <Project>" as C2.1
participant "projectListByUserDtoList : List <ProjectDTO>" as C5
participant "projectListByUserDto : ProjectDTO" as C6
participant "proj : Project" as C3
participant ": ProductBacklogMappper" as C3.1
participant "productBacklog : ProductBacklog" as C4
participant "userStoryList : LinkedList <UserStory>" as C4.1
participant "userStoryListDtoList : LinkedList <UserStoryDto>" as C7
participant "userStoryListDto : UserStoryDto" as C8

activate User

User -> System: Get list of project where is associated
System -> Ctrl: getProjectListByUserEmail(email)
Ctrl -> C1: getProjectStore()
C1 --> Ctrl: projStore
Ctrl -> C2: getProjectListByUserEmail(email)

C2 -> C2.1 ** : createProjectList

 loop for each known project in projectList has email
C2->C2.1 : addProjectList
C2.1-->C2 : true
end
C2 --> Ctrl: projectListByUser
Ctrl-> C2.1.0: toDtoByUser(projectListByUser)
C2.1.0->C5 ** : create()

loop for each known project in projectList
C2.1.0->C2.1: code = getCode()
deactivate C2.1
C2.1.0->C2.1: projectName = getprojectName()
deactivate C2.1
C2.1.0->C2.1: description = getDescription()
deactivate C2.1
C2.1.0->C6 ** : create (code, projectName, description)
C2.1.0->C5: add(projectListByUserDto)
C5-->C2.1.0: true
end

C2.1.0 --> Ctrl: projectListByUserDtoList
Ctrl --> System: projectListByUserDtoList
System --> User : Shows projectList to select project

User -> System: Choose project to access product backlog
System -> Ctrl: getUsSortedByPriority()
Ctrl -> C2 : getProjectByCode(code)
C2 --> Ctrl : proj
Ctrl-> C3 : getProductBacklog()
C3 --> Ctrl : productBacklog
Ctrl -> C4 : getUsSortedByPriority()
C4 -> C4.1 ** : createUserStoryList

loop for each known userStory in productBacklog
C4->C4.1 : addUserStoryList
C4.1-->C4 : true
end

C4-->Ctrl : userStoryList
Ctrl->C3.1: toDto(userStoryList)
C3.1->C7 ** : create()

loop for each known userStory in productBacklog
C3.1->C4: name = getName()
deactivate C4
C3.1->C4: userStoryStatus = getUserStoryStatus()
deactivate C4
C3.1->C4: priority = getPriority()
deactivate C4
C3.1->C4: description = getDescription()
deactivate C4
C3.1->C8 ** : create(name, userStoryStatus, priority, description)
C3.1->C7: add(userStoryListDto)
C7-->C3.1: true
end
C3.1 --> Ctrl : userStoryListDtoList
Ctrl --> System : userStoryListDtoList
System --> User : Shows list of User Stories sorted

@enduml