@startuml
'https://plantuml.com/sequence-diagram

title US017 - As Authenticated User, I want to get a list of all projects I'm currently allocated to

autonumber

actor "Authenticated User" as actor
participant ": GetCurrentProjectsByUserRoute" as route
participant ": GetCurrentProjectsByUserController" as ctrl
participant "dataDto : DataDto" as dataDto
participant ": GetCurrentProjectsByUserService" as srv
participant ": IRepositorySystemUser" as userStore
participant ": IRepositoryResource" as resStore
participant "userResources : List<Resource>" as resList
participant ": FilterResourcesService" as dsrv
participant "currentUserResources : List<Resource>" as resList2
participant "currentResourcesByUser : List<Resource>" as resList3
participant "resourceProjects : List<ProjectId>" as resList4
participant "res : Resource" as res
participant "projId : ProjectId" as pId
participant "projects : List<Project>" as projList
participant ": IRepositoryProject" as projStore
participant "proj : Project" as proj
participant ": GetCurrentProjectsByUserMapper" as map
participant "projectsDto : List<ProjectDto>" as listDto
participant "projDto : ProjectDto" as dto
participant "ProjectsResponse : ResponseEntity" as json

activate actor
autoactivate on

actor -> route : GET /users/{userId}/resources?date={date}
route -> ctrl : getCurrentProjectsByUser()
ctrl -> srv : getCurrentProjectsByUser(dataDto)
note over ctrl, srv : The object dataDto is created with variables userId and date in the path.
srv -> userStore : existById(dataDto.userId) : true
deactivate
srv -> resStore : findAllByUser()
resStore --> resList** : create()
resStore --> srv : userResources
srv -> dsrv : currentResourcesByDate(userResources, dataDto.date)
dsrv --> resList2**: create()
loop for all known resource in the list
dsrv -> resList : get(i) : res
deactivate
dsrv -> res : isCurrentByDate(dataDto.date)
res --> dsrv : result
opt if result is true
dsrv -> resList2 : add(res) : true
deactivate
end
end
dsrv --> srv : currentUserResources
srv -> dsrv : listProjectsOfResources(currentUserResources)
dsrv --> resList4**: create()
loop for all known resource in the list
dsrv -> resList3 : get(i) : res
deactivate
dsrv -> res : getProjectId() : projId
deactivate
dsrv -> resList4 : add(projId) : true
deactivate
end
dsrv --> srv : currentResourceProjectsByUser
srv --> projList**: create()
loop for all known projectId in the list
srv -> projStore : findById(projId)
projStore --> srv : proj
srv -> projList : add(proj) : true
deactivate
end
srv -> map : model2Dto(projects)
map --> listDto**: create()
note over map : The sequence of this method are hidden to simplify the diagram.
map --> srv : projectsDto
srv --> ctrl : projectsDto
ctrl --> json**: create()
note over ctrl, json : The Controller uses the Response Entity class to create a response in JSON format using the dto received from Service layer and defining the HTTP status.
ctrl --> route : projectsResponse
route --> actor : Show all projects that the user are currently allocated to


@enduml