@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US005 - As a Director, I want to create/register a new project

class CreateProjectUI {

}

class CreateProjectController {
    +createProject(name,description,startDate,numberOfSprints,typology, business, customer, budget)
    +getBusinessSectorStore()
    +getCustomerStore()
    +getTypologyStore()
}

class Company {
    +getProjectStore()
}

class ProjectStore {
+createProject(name,description,startDate,numberOfSprints,typology, business, customer, budget)
}

class Project {
-name : String
-description : String
-startDate : LocalDate
-numberOfSprints : int
-typology : Typology
-customer : Customer
-sector : BusinessSector
+Project(name,description,startDate,numberOfSprints,typology, business, customer, budget)
}

class CustomerStore {
+getCustomerById(String customer)
}

class TypologyStore {
+getTypologyById(String typology)
}

class BusinessSectorStore {
+getBusinessSectorById(String sector)
}

CreateProjectUI ..> CreateProjectController

CreateProjectController ..> Company
CreateProjectController ..> CustomerStore
CreateProjectController ..> TypologyStore
CreateProjectController ..> BusinessSectorStore


Company "1" *-- "1" ProjectStore: has
Company "1" *-- "1" CustomerStore: has
Company "1" *-- "1" TypologyStore: has
Company "1" *-- "1" BusinessSectorStore: has
ProjectStore "1" *-- "0..*" Project: has


@enduml