@startuml
'https://plantuml.com/class-diagram

title US005 - As a Director, I want to create/register a new project

autoactivate on
autonumber

actor "Director" as director

participant ":CreateProjectUI " as ui
participant ":CreateProjectController " as controller
participant ":ProjectService " as service
participant ":ProjectFactory " as factory
participant ":ProjectMapper " as mapper
participant "projDTO:ProjectDTO " as dto
participant ":ProjectStore " as store
participant "proj:Project " as project

activate director
director -> ui: Requests creation of a new Project
ui --> director: Requests Project Data

director -> ui: Types required project data
ui -> controller: createProject(dto)

controller -> service: createProject(dto)
service -> factory: createAndSaveProject(dto.getName, dto.getDescription, dto.getStartDate, dto.getNumberOfSprints, dto.getBudget)

factory -> project**: createProject(dto.getName, dto.getDescription, dto.getStartDate, dto.getNumberOfSprints, dto.getBudget)
activate project

project --> factory: proj

factory -> store: saveProject(proj)
store -> store: add(proj)
deactivate store
deactivate store

factory -> mapper: toDTO(proj)

mapper -> dto**: toDTO(proj)
activate dto
deactivate mapper

dto --> factory: projDTO

factory --> service: projDTO

service --> controller: projDTO

controller --> ui: projDTO

ui --> director: confirms successful creation

@enduml

