@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US033 - As SM/Team Member, I want to register work done on a Task

class RegisterWorkToTaskUI {
}

class RegisterWorkToTaskController {
}

class Company {
    +getProjectStore()
}

class ProjectStore {
+getCurrentProjectsByUserEmail(String email)
+getProjectByCode(String code)
}

class Project {
-code : String
-projectName : String
+getProductBacklog()
}

class SprintList {
}

class Sprint {
}

class TaskList {
}

class Task {
+createTaskEffort(workHours, workDay, comment, attachment, user)
+saveTaskEffort(effort)
+validateTaskEffort(effort)
+add(effort)
+updateWorkDone(effort)
+updatePercentExecution(effort)
}

class TaskEffort {
-workHours : double
-workDate : LocalDate
-comment : String
-attachment : String
-user : SystemUser
+createTaskEffort(workHours, workDate, comment, attachment, user)
}

RegisterWorkToTaskUI ..> RegisterWorkToTaskController

RegisterWorkToTaskController ..> Company
RegisterWorkToTaskController ..> ProjectStore
RegisterWorkToTaskController ..> Project

Company "1" -> "1" ProjectStore: has
ProjectStore "1" *-- "0..*" Project: has
Project "1" *-- "1" SprintList
SprintList "1" *-- "0..*" Sprint
Sprint "1" -> "1" TaskList: has
TaskList "1" *-- "0..*" Task
Task "1" *-- "0..*" TaskEffort: has
@enduml