@startuml
'https://plantuml.com/sequence-diagram

title US033 - As SM/Team Member, I want to register work done on a Task (PARTIAL)

autoactivate on
autonumber

participant ": RegisterWorkToTaskController" as Ctrl
participant ": Company" as company
participant ": RegisterWorkToTaskMapper" as mapper
participant "userStoryIdDTO: UserStoryIdDTO" as userStoryIdDTO
participant "userStoryList : Sprintbacklog" as sprintBacklog
participant "userStory : UserStory" as userStory
participant "taskList : TaskList" as taskList
participant "taskIdDTOList: List<TaskIdDTO>" as taskIdDTOList
participant "taskIdDTO: TaskIdDTO" as taskIdDTO

[o->Ctrl: getTasks(userStoryIdDTO)
Ctrl->mapper: userStoryIdDTOToUserStoryId(userStoryIdDTO)
mapper->userStoryIdDTO: getId()
userStoryIdDTO-->mapper: userStoryId
mapper-->Ctrl: userStoryId
Ctrl->sprintBacklog: getUserStoryById(userStoryId)
loop for each userStory in sprintBacklog
sprintBacklog->userStory: hasId(userStoryId)
userStory-->sprintBacklog: true
end
sprintBacklog-->Ctrl: userStory

Ctrl->userStory: getTaskList()
userStory-->Ctrl: taskList
Ctrl->taskList: getTaskList()
taskList-->Ctrl: taskList

Ctrl->mapper: taskListToTaskListDTO(taskList)
mapper->taskIdDTOList **: create()
loop for each task in taskList
mapper->taskList: get(i)
taskList-->mapper: task
mapper->mapper: taskIdDTO = taskIdToTaskIdDTO(task)
mapper->mapper:taskIdDTO = task.getId()
deactivate mapper
mapper->taskIdDTO**: create(taskIdDTO)
deactivate mapper
mapper->taskIdDTOList: add(taskIdDTO)
taskIdDTOList-->mapper: true
end
mapper-->Ctrl: taskIdDTOList
[<--Ctrl: taskIdDTOList
@enduml