@startuml
'https://plantuml.com/sequence-diagram

title US033 - As SM/Team Member, I want to register work done on a Task (PARTIAL)

autoactivate on
autonumber

participant ": RegisterWorkToTaskController" as Ctrl
participant ": RegisterWorkToTaskMapper" as mapper
participant "proj : Project" as project
participant "sprintList\n: SprintList" as sprintList
participant "sprintIdNameDTOList\n: List<SprintIdNameDTO>" as sprintIdDTOList
participant "sprintIdNameDTO\n: SprintIdNameDTO" as sprintIdDTO

[o->Ctrl: getProjectSprints()
Ctrl->project: getSprintList()
project-->Ctrl: sprintList
Ctrl->sprintList: getSprintList()
sprintList-->Ctrl: sprintList

Ctrl->mapper: sprintListToSprintListDTO(sprintList)
mapper->sprintIdDTOList **: create()
loop for each sprint in sprintList
mapper->sprintList: get(i)
sprintList-->mapper: sprint
mapper->mapper: sprintToSprintIdNameDTO(sprint)
mapper->sprintIdDTO**: create(sprint.getIdSprint(), sprint.getName())
deactivate mapper
mapper->sprintIdDTOList: add(sprintIdNameDTO)
sprintIdDTOList-->mapper: true
end
mapper-->Ctrl: sprintIdNameDTOList
[<--Ctrl: sprintIdNameDTOList

@enduml