@startuml
'https://plantuml.com/class-diagram

title US008 - As a Project Manager I want to edit some project information

autoactivate on
autonumber


participant ":EditProjectRoute " as route
participant "inDto: \nEditProjectDTO " as inDto
participant ":ProjectController " as controller
participant ":EditProjectService " as service
participant ":IProjectRepo " as store
participant ":ProjectMapper " as mapper
participant "outputDTO: \nOutputProjectDTO " as dto
participant "exception: \nException" as exc
participant "proj:Project " as project
participant "response: \nResponseEntity" as json


[o->  route: PATCH /projects/{id}
route -> controller: editProject(inDto)

note right route: Json object was deserialize to a EditProjectDto object

controller -> service: editProject(inDto)

note over service : The creation of the id are hidden to simplify the diagram.

service -> store: updateProjectPartially(projectId, editProjectInfoDTO)

ref over store: [[US008jpaGet-SD.puml]]

store --> service: proj

alt if project exist

service -> project: editProjectInfo(inDto)

note over project : The changes of attributes are hidden to simplify the diagram .

project --> service : result

service -> store : save(proj)

ref over store: [[US008jpaUpdate-SD.puml]]
store --> service : proj

service -> mapper: model2DTO(proj)

mapper -> dto**: model2DTO(proj)

mapper --> service: outputDto

else if project does not exist

service --> exc** : create(errorMessage)

end

service --> controller: outputDto

controller --> json**: create(outputDto)

controller --> route: response


[<-- route: Show the modified project

@enduml

