@startuml
'https://plantuml.com/sequence-diagram

title US024 - As Administrator, I want to get a list all user accounts and their status

autoactivate on
autonumber

actor "User" as User
participant ":System" as System

activate User

User -> System: Get list all user accounts and their status
System --> User: Show requested list user accounts with status

@enduml