@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model extract

class Company{
}

class SystemUser{
      - userName
      - email
      - photo
      - password
      - function
      - activateUser
      }

class ActivationInfo{
- code
- link
- activated
}
class UserProfile{
- idProfile
- userProfileName
}
class Request{
- idRequest
- requestDate
- requestStatus
}

SystemUser "1" -- "1" ActivationInfo: belongs to
SystemUser "1" <-- "*" Request: sent by
SystemUser "*" -- "1" Company: employed by
UserProfile "1..*" -- "*" SystemUser: is assigned

@enduml