@startuml
'https://plantuml.com/class-diagram

title Domain Model

entity User #Gold{
userName
photo
encryptedPassword
function
isActive
requestedProfiles
}


entity UserProfile #Yellow{
userProfileId
}

User "*" -> "1.*" UserProfile: is assigned to

@enduml