@startuml

hide circle
skinparam classAttributeIconSize 0

title "US006 - As Administrator, I want to update profiles assigned to a user account."

class UpdateUserProfileUI {
}

class UpdateUserProfileController {
+UpdateUserProfileController(company)
+getUser(email)
+getUserProfileList()
+updateProfile(user, oldProfile, newProfile)
}

class Company {
+Company
+getSystemUserStore()
+getUserProfileStore()
}

class UserProfileStore {
+UserProfileStore()
getUserProfileList()
}

class SystemUserStore {
+SystemUserStore()
+getUserByEmail(email)
}

class SystemUser {
+SystemUser()
+isYourEmail(email)
+updateProfile(oldProfile, newProfile)
}

UpdateUserProfileUI ..> UpdateUserProfileController
UpdateUserProfileController ..> Company
UpdateUserProfileController ..> UserProfileStore
UpdateUserProfileController ..> SystemUserStore
UpdateUserProfileController ..> SystemUser

Company "1" o-- "1" UserProfileStore
Company "1" o-- "1" SystemUserStore
SystemUserStore "1" *-- "*" SystemUser

@enduml