@startuml
'https://plantuml.com/sequence-diagram

title US018 - As PO/SM/TeamMember, I want to consult the Product Backlog, i. e. to get the list of user stories sorted by priority

autoactivate on
autonumber

actor "PO/SM/TeamMember" as User
participant ": ProductBacklogUI" as System
participant ": ProductBacklogController" as Ctrl
participant ": Company" as C1
participant "projStore : ProjectStore" as C2
participant "projectListByUser : List <Project>" as C2.1
participant "proj : Project" as C3
participant "productBacklog : ProductBacklog" as C4
participant "userStoryList : LinkedList <UserStory>" as C4.1

activate User

User -> System: Get list of project where is associated
System -> Ctrl: getProjectListByUserEmail(email)
Ctrl -> C1: getProjectStore()
C1 --> Ctrl: projStore
Ctrl -> C2: getProjectListByUserEmail(email)
 loop for each know project
C2 -> C2.1 ** : createProjectList
end


C2 --> Ctrl: projectListByUser
Ctrl --> System: projectListByUser
System --> User : Shows projectList to select project

User -> System: Choose project
System -> Ctrl: getProject(code)
Ctrl -> C2 : getProjectByCode(code)
C2 --> Ctrl : proj
Ctrl --> System : proj
System --> User :Shows project information

User -> System: Access product backlog
System -> Ctrl: getUsSortedByPriority()
Ctrl-> C3 : getProductBacklog()
C3 --> Ctrl : productBacklog
Ctrl -> C4 : getUsSortedByPriority()
C4 -> C4.1 ** : createProjectList
C4-->Ctrl : userStoryList
Ctrl --> System : userStoryList
System --> User : Shows list of User Stories sorted

@enduml