@startuml
'https://plantuml.com/sequence-diagram

title US015 System Sequence Diagram

autoactivate on
autonumber

actor "Director" as User
participant ":System" as System

activate User

User -> System: wants to get a list of all projects
System->System: get the projects list
deactivate System
System-->User: return the list of all projects

@enduml