@startuml
'https://plantuml.com/class-diagram

'hide circle
skinparam classAttributeIconSize 0

title US010 - As Authenticated user, i want to update its own data (e.g. photo, function...)

class UpdatePersonalDataUI {
}

class UpdatePersonalDataController {
+getUser(email)
+updateSystemUser(username, function, photo)
}

class Company {
+getSystemUserStore()
}

class SystemUserStore {
+getUserByEmail(email)
}


class SystemUser {
username : String
email : String
photo : String
password : String
passwordConfirmation : String
function : String
activateUser : boolean = False
+SystemUser(username, email, photo, password, passwordConfirmation, function, profile)
+isYourEmail(email)
+setAllData(username, function, photo)
+setUsername(username)
+setFunction(function)
+setPhoto(photo)
}


UpdatePersonalDataUI ..> UpdatePersonalDataController

UpdatePersonalDataController ..> Company
UpdatePersonalDataController ..> SystemUserStore
UpdatePersonalDataController ..> SystemUser


Company "1" o-- "1" SystemUserStore: has
SystemUserStore "1" *-- "0..*" SystemUser: has

@enduml