@startuml
'https://plantuml.com/sequence-diagram

title US010 - As Authenticated User, i want to update its own data (e.g. photo, function, ...)

autoactivate on
autonumber

actor "Authenticated User" as User
participant ":System" as System

activate User

User -> System: wants to update its own information
System->System: update the user
deactivate System
System-->User: Show to Authenticated User its own information modified

@enduml