@startuml
'https://plantuml.com/sequence-diagram

title US010 - As Authenticated User, i want to update its own data (e.g. photo, function,...)

autoactivate on
autonumber

participant ":UpdatePersonalDataRoute" as route
participant ":SystemUserController" as Ctrl
participant ":UpdatePersonalDataService" as service
participant ":UpdateUserDTO" as dto
participant "systemUser : ISystemUserRepo" as iRepo
participant ":SystemUser" as systemUser
participant ":SystemUserMapper" as mapper
participant "outPutUpdateUserDTO : OutPutUpdateUserDTO" as outPutDTO

[o-> route: PUT/{ID}/edit(json)
route -> Ctrl: updatePersonalData(json)
note right
Change from json to dto hidden to simplify diagram
end note
Ctrl -> service: updatePersonalData(updateUserDTO)
service -> dto: email = getEmail()
deactivate
service -> dto: username = getUserName()
deactivate
service -> dto: function = getFunction()
deactivate
service -> dto: photo = getPhoto()
deactivate
note right
All the following objects were created with factories, but the process is hidden in SD to simplify
end note
service -> iRepo: findSystemUserByID(email)
iRepo --> service: systemUser
service -> systemUser: editPersonalData (username, function, photo)
systemUser --> service: true
service -> mapper: modelToDTO(systemUser)
mapper -> outPutDTO**: create()
mapper --> service: outPutUpdateUserDTO
service --> Ctrl: outPutUpdateUserDTO
Ctrl --> route: outPutUpdateUserJSON
[<--route : Informs Operation Success


@enduml