@startuml

skinparam classAttributeIconSize 0

title US012 - "As Director, I want to create a new project typology."

package "Infraestructure" #application {
    class CreateTypologyRoute <<Component>>{
    }
}

package "Interface Adapter" #technology {
    class CreateTypologyController <<Component>>{
    +createTypology(inputDto)
    }

    class TypologyRepository <<Repository>>{
    +RepositoryTypology()
    +findById (id_Typology)
    +findAll ()
    +saveTypology (id_Typology)
    +validateTypology (id_Typology)
    +delete(id_Typology)
    }
}

package "DTO" #motivation {
    class TypologyDTO <<Component>> {
    +TypologyDTO()
    }

    class TypologyMapper <<Component>> {
    +TypologyMapper (typology)
    +toDto (typology)
    }
}

package "App Service API/Use Case Service" #implementation {
    package "App Service" {
        class CreateTypologyService <<Service>>{
        +CreateTypologyService()
        +createAndSaveTypology(inputDto)
        +
        }
    }
    package "Repositories Interface" {
        class IRepositoryTypology <<(I, Violet) Interface>> {
            +IRepositoryTypology()
            +findById (id_Typology)
            +findAll ()
            +saveTypology (id_Typology)
            +validateTypology (id_Typology)
            +delete(id_Typology)
        }
    }
}


package "Entity/Core/Domain" #strategy {
    package "Factory" {
        class TypologyFactory <<"Factory">> {
        +create (inputDto)
        }
    }
    package "Aggregate" {
        class Typology <<Root>>{
            +Typology (id_Typology)
        }
    }
    package "Value Object"  {
        class ID_Typology <<Value Object>>{
        +ID_Typology (description)
        }
        class Description {
        +Description(inputDto.description)
        }
    }
}

CreateTypologyRoute -down..> CreateTypologyController
CreateTypologyController -down..> CreateTypologyService
CreateTypologyController -right..> TypologyMapper
CreateTypologyService -right..> TypologyMapper
TypologyMapper -left..>TypologyDTO
CreateTypologyService -down..> TypologyFactory
TypologyFactory -left..> Typology
CreateTypologyService -right..> IRepositoryTypology
IRepositoryTypology -up[hidden]..> TypologyRepository
class TypologyRepository implements IRepositoryTypology
TypologyFactory -down..> ID_Typology
TypologyFactory -left..> Description

@enduml