@startuml

title US012 - "As Director, I want to create a new project typology."

autoactivate on
autonumber

actor "Director" as Director
participant ":System" as System

Director -> System: Starts the creation of a new typology
System -> System: create Typology
deactivate
return Informs operation success

@enduml