@startuml

title US012 - "As Director, I want to create a new project typology."

autoactivate on
autonumber

participant ":CreateTypologyRoute" as Router
participant "Ctrl:CreateTypologyController" as Controller
participant "service:CreateTypologyService" as Service
participant "factTypo:ITypologyFactory" as Factory
participant "newTypo:Typology" as Typology
participant "repoTypo:IRepositoryTypology" as Repository
participant "savedTypoDto:DtoTypology" as outputDTO
participant "mapper:TypologyMapper" as Mapper

[o-> Router: Post/Typologies/(inputDto)
Router -> Controller: createTypology (inputDto)
Controller -> Service: createAndSaveTypology(newTypoDto)
Service -> Factory: create(newTypoDto)
Factory --> Typology**: create(newTypoDto.description)
return newTypo
Service -> Service: saveTypology(newTypo)
Service -> Repository: saveTypology(newTypo)
Repository -> Repository: existsByTypologyId(newTypo)
deactivate Repository
return true
deactivate Service
Service -> Mapper: toDTO(newTypo)
Mapper --> outputDTO**: create(newTypoAttr)
return savedTypoDto
return savedTypoDto
return outputDto
[<--o Router: response

@enduml