@startuml

hide circle
skinparam classAttributeIconSize 0

title US012 - "As Director, I want to create a new project typology."

class CreateUpdateUserProfileUI {
}

class CreateUpdateUserProfileController {
+CreateUpdateUserProfileController()
+createTypology (description)
}

class Company {
+Company()
+getTypologyStore()
}

class TypologyStore {
+TypologyStore()
+createTypology (description)
+saveTypology (typo)
+validateTypology (typo)
}

class Typology {
+Typology (description)
}

CreateUpdateUserProfileUI ..> CreateUpdateUserProfileController
CreateUpdateUserProfileController ..> Company
CreateUpdateUserProfileController ..> Typology
Company "1" o-- "1" TypologyStore: has
TypologyStore "1" *-- "*" Typology: has

@enduml