@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US026 - As Administrator, I want to activate a user account

class ActivateUserAccountUI {

}

class ActivateUserAccountController {
    +getUser(email)
}

class Company {
    +activateUser(email)
}

class SystemUserStore {
+getUserByEmail(email)
}

class SystemUser {
-code : String
-photo: String
-username: String
-password: String
-function: String
-inactivateUser: boolean

+setActivateUser(email)
}

ActivateUserAccountUI ..> ActivateUserAccountController
ActivateUserAccountController ..> Company
ActivateUserAccountController ..> SystemUserStore
ActivateUserAccountController ..> SystemUser

Company "1" o- "1" SystemUserStore: has
SystemUserStore "1" *- "1" SystemUser: has

@enduml