@startuml
'https://plantuml.com/sequence-diagram

title US007 - As Director, I want to associate a human resource (user) to a project

autoactivate on
autonumber

participant ":CreateResourceInAProjectRoute" as Route
participant "inDto :CreateResourceDto" as dto
participant ":ResourceController" as Ctrl
participant "srv:CreateResourceInAProjectService" as srv
participant "sysUsRepo:ISystemUserRepo" as systemUserStore
participant "projRepo:IProjectRepo" as projectStore
participant "resFac:IResourceFactory" as resourceFactory
participant "resRepo:IResourceRepo" as resourceStore
participant "res : Resource" as resource
participant "projectTeam : List<Resources>" as projectTeam
participant "userResources : List<Resources>" as resourceProjects
participant "project:Project" as project
participant "dsrv:DomainServiceResourceValidation" as domainService
participant "map:ResourceMapper" as map
participant "outDto:OutputResourceDto" as outDto
participant "exception :Exception" as exc
participant "finalResult :Result" as result
participant "responseJson:ResponseEntity" as json

[o-> Route:  POST/resources(json)
Route -> Ctrl: associateResource (inDto)
note right Route: Json object was deserialize to a CreateResourceDto object
Ctrl -> srv: createAndSaveResource (inDto)
note over srv : The creation of these ids are hidden to simplify the diagram.
srv -> systemUserStore: findUserResult : existsBySystemUserId(systemUserId)
deactivate systemUserStore
srv -> projectStore: findProjectResult : findByProjectId(projectId)
deactivate projectStore
alt if user and project exist
srv -> resourceFactory: createResource(inDto)
note over resourceFactory : All parameters (value objects) are instantiated in their own factory.
resourceFactory -> resource**: createResource(resourceId, endDate, costPerHour, allocation)
opt if the request has a role
note over resourceFactory : Chose a role to creation of the resource are optional
resourceFactory -> resource :defineRole(role)
deactivate resource
end
resourceFactory --> srv: res
srv -> resourceStore: findAllByProjectId(projectId)
resourceStore-> projectTeam**: create()
resourceStore --> srv: projectTeam
srv -> resourceStore: findAllBySystemUserId(systemUserId)
resourceStore -> resourceProjects**: create()
resourceStore --> srv: userResources
srv -> domainService: validateResourceCreation(project, res, projectTeamList, resourceProjectsList)
domainService -> project: isInsideProjectPeriod(date)
deactivate
domainService -> domainService: validateAllocation(resourceProjectsList, res)
deactivate
domainService -> domainService: validateProjectRole(res, projectTeamList)
deactivate
domainService --> srv: validateNewResourceResult
alt if the criteria of the allocation a resource in a project are met
srv -> resourceStore: save(res)
resourceStore --> srv: saveResult
alt if the new resource was successfully saved
srv -> map : model2Dto(res)
map --> outDto** : create()
map --> srv : outDto
srv --> result** : create(outDto)
else new resource was not saved
srv --> exc** : create(errorMessage)
end
else new resource not be valid
srv --> exc** : create(errorMessage)
end
else user or project does not exist
srv --> exc** : create(errorMessage)
end
srv --> Ctrl: finalResult
Ctrl --> json**: create(finalResult)
Ctrl --> Route: responseJson
[<--Route: response

@enduml