@startuml
'https://plantuml.com/class-diagram

'hide circle
skinparam classAttributeIconSize 0

title US007 - As Director, I want to associate a human resource (user) to a project

class AssociateResourceUI {

}

class AssociateResourceController {
    +getProjectList()
    +getSystemUserList()
    +associateResource(email, projectCode, startDate, endDate, costPerHour, percentageOfAllocation)
}

class Company {
    +getProjectStore()
    +getSystemUserStore()
}

class ProjectStore {
+getProjects()
+getProjectByCode(code)
+validateAllocation(user, percentageOfAllocation, startDate, endDate)
}

class Project {
code : String
projectName : String
description : String
customer : Customer
typology : Typology
projectStatus : ProjectStatus
productBacklog : ProductBacklog
businessSector : BusinessSector
projectTeam : ProjectTeam
startDate : LocalDate
endDate : LocalDate
numberOfSprints : int
budget : double
sprintDuration : int
+hasCode(code)
+getProjectTeam()
+getTeamMemberByIndex(index)
}

class SystemUserStore {
+getSystemUsers()
+getUserByEmail(email)
}

class SystemUser {
username : String
email : String
photo : String
password : String
passwordConfirmation : String
function : String
activateUser : boolean = False
+SystemUser(username, email, photo, password, passwordConfirmation, function, profile)
+isYourEmail(email)
}


class Resource {
user : SystemUser
role : ProjectRole
startDate : LocalDate
endDate : LocalDate
costPerHour : double
percentageOfAllocation : double
+getUser()
+getPercentageOfAllocation()
+checkAllocationPeriod(startDate, endDate)
}

AssociateResourceUI ..> AssociateResourceController

AssociateResourceController ..> Company
AssociateResourceController ..> ProjectStore
AssociateResourceController ..> SystemUserStore
SystemUserStore ..> SystemUser
ProjectStore ..> Project
ProjectStore ..> Resource


Company "1" o-- "1" SystemUserStore: has
SystemUserStore "1" *-- "0..*" SystemUser: has


@enduml