@startuml
'https://plantuml.com/class-diagram

title US004 - As Administrator, I want to search for users

skinparam classAttributeIconSize 0

package "System" <<Rectangle>> {

'-------------------INFRASTRUCTURE-----------------------'
package "Infrastructure" <<Rectangle>> #lightblue  {
class "CreateResourceInAProjectRoute" as route << Component >>
}




'-------------------INTERFACE ADAPTERS-------------------'
package "Interface Adapters" <<Rectangle>> #lightgreen {
package "Controllers" <<rectangle>>{
class "ResourceController" as ctrl << Component >> {
}
}

package "Repositories" <<rectangle>>{
class "ResourceStore" as resStore << Repository >> {
}
class "SystemUserStore" as userStore << Repository >> {
}
class "ProjectStore" as projStore << Repository >> {
}
}
}



'-------------------APPLICATION SERVICE------------------'
package "Application Service" <<Rectangle>> #lightpink{
package "App Services" <<rectangle>>{
class "CreateResourceInAProjectService" as srv << Service >> {
}
}
package "IRepositories" <<rectangle>>{
interface "IResourceRepo" as resRepo{
}
interface "ISystemUserRepo" as userRepo{
}
interface "IProjectRepo" as projRepo{
}
}
}




'-------------------DOMAIN-------------------------------'
package "Domain" <<Rectangle>> #burlywood{
package "Domain Service" <<Rectangle>>{
entity "Service" as dsrv << Root >>
}
package "Aggregates" <<rectangle>>{
package "Resource" <<Rectangle>>{
entity "Resource" as res << Root >>
}
package "SystemUser" <<Rectangle>>{
entity "SystemUser" as user << Root >>
}
package "Project" <<Rectangle>>{
entity "Project" as project << Root >>
}
}
package "Value Object" <<rectangle>>{
class "ResourceId" as resId << Value Object >>
class "SystemUserId" as userId << Value Object >>
class "ProjectId" as projId << Value Object >>
}
}


'-------------------DTO----------------------------------'
package "DTO" <<rectangle>>{
class "ResourceMapper" as map <<Component>> {
+ model2Dto()
}
class "createResourceDto" as inDto <<Component>>
class "OutputResourceDto" as outDto <<Component>>
}



'-------------------OTHERS-------------------------------'
class "ResponseEntity" as json <<Component>>
}



'-------------------RELATIONSHIPS------------------------'
route ..> ctrl
ctrl .d..> srv
srv .d..> dsrv

srv .r.> userRepo
srv .r.> projRepo
srv .r.> resRepo

userRepo <|.u. userStore
projRepo <|.u. projStore
resRepo <|.u. resStore

srv .l.> map
map ..> outDto
ctrl ..> inDto
srv ..> inDto

ctrl .l.> json

project *--> projId
user *--> userId
res *--> resId
resId o--> projId
resId o--> userId



@enduml