@startuml
title "US019 - As a team member I want to set the effort of a user story"

autoactivate on
autonumber

participant ": UserStoryRoute" as Route
participant ": UserStoryController" as Ctrl
participant ": UserStoryService" as Service
participant "iUsIdFactory : IUserStoryIDFactory" as IdFactory
participant "userStoryID: UserStoryID" as ID
participant ": IUserStoryRepo" as Repo
participant "usHourFactory: IUsHourFactory" as EffortFactory
participant "usHour: UsHour" as Effort
participant "userStory: UserStory" as US
participant ": UserStoryJpaRepository" as Driver
participant ": UserStoryMapper" as usMapper
participant "exception: \nException" as exc
participant "updateDto : \n OutputUserStoryDTO" as outDto
participant "response: \nResponseEntity" as json

[o-> Route: Asks for estimate the effort of a user story
Route -> Ctrl: estimateEffort(updateDTO)
Ctrl -> Service: timeEffortEstimation(id, updateDTO)
Service -> Service: createUserStoryIdByStringInputFromController(id)
Service -> IdFactory: create(pId, uTitle)
IdFactory --> ID**: create()
return userStoryID
return userStoryID
Service -> Repo: findByUserStoryId(userStoryID)
return userStory
opt if timeEstimate is different then 0
    Service -> EffortFactory: createTimeEffort(updateDTO.timeEstimate)
    EffortFactory -> Effort**: create()
    return usHour
    Service -> US: updateTimeEstimate(usHour)
    deactivate US
end
Service -> Repo: update(userStory)
ref over Repo: [[US019-SD-JPA.puml]]
return updated
opt if the new userstory already exist
    Service --> exc** : create(errorMessage)
end
Service-> usMapper : toDto(updated)
usMapper-> outDto **:create()
usMapper --> Service: updatedDto
Service --> Ctrl: updatedDto
Ctrl --> json**: create(updatedDto)
return response
return response

@enduml