@startuml
'https://plantuml.com/sequence-diagram

title US018 - As PO/SM/TeamMember, I want to consult the Product Backlog, i. e. to get the list of user stories sorted by priority

autoactivate on
autonumber

actor "TeamMember" as User
participant "EffortUserStoryUI" as System
participant ":EffortUserStoryController" as Ctrl
participant ": Company" as C1
participant "projStore : ProjectStore" as C2
participant "projectList: List <Project>" as C2.1
participant "proj : Project" as C3
participant "sprintList: SprintList" as C4
participant "sprint: Sprint" as C5
participant "sprintbacklog: SprintBacklog" as C6
participant "usOfSprint: UserStoryOfSprint" as C7

activate User

User -> System: Get list of project where is associated
System -> Ctrl: getProjectListByUserEmail(email)
Ctrl -> C1: getProjectStore()
C1 --> Ctrl: projStore
Ctrl -> C2: getProjectListByUserEmail(email)

C2 -> C2.1 ** : createProjectList
loop
C2-> C2.1 : addProjectToList
C2.1 --> C2 : true
end


C2 --> Ctrl: projectListByUser
Ctrl --> System: projectListByUser
System --> User : Shows projectList
User -> System: Choose project
System -> Ctrl: getProjectByCode(code)
Ctrl -> C2 : getProjectByCode(code)
C2 --> Ctrl : proj
Ctrl --> System : proj
System --> User :Shows project choosen

User -> System: Access sprint list
System -> Ctrl: getSprintList()
Ctrl-> C3 : getSprintList()
C3 --> Ctrl : sprintStore
Ctrl -> C4 : getSprintList()
C4 --> Ctrl : sprint list
Ctrl --> System : sprint list
System --> User : Show the sprint list

User -> System: Choose Sprint
System -> Ctrl: getSprint(id)
Ctrl -> C5 : getSprint(id)
loop
C5-> C6 : hasSprintID(id)
end
C6-->C5 : true
C5 -->Ctrl: sprint
Ctrl --> System: sprint
System --> User: Show the sprint

User-> System : Access Sprint Backlog
System -> Ctrl: getSprintBacklog()
Ctrl -> C5 : getSprintBacklog()
C5 --> Ctrl : sprintBacklog
Ctrl --> System: sprintBacklog
System --> User : Show sprint backlog

User -> System: Choose User Story of Sprint
System -> Ctrl: getUserStory(id_UserStoryOfSprint)
Ctrl -> C6: getUserStory(id_UserStoryOfSprint)
loop
C6 -> C7 : hasCode (id_UserStoryOfSprint)
end
C7 --> C6 : true
C6 -->Ctrl : userStoryOfSprint
Ctrl --> System: userStoryOfSprint
System --> User: Show user story of Sprint

User -> System: Set User Story Effort
System -> Ctrl: setEffort (effort)
Ctrl -> C7 : setEstimateEffort (effort)
C7 -> C7 : validateEffort()
C7 --> Ctrl: true
Ctrl --> System: true
System --> User: true

@enduml