@startuml
'https://plantuml.com/sequence-diagram

title US019 - As a team member I want to set the effort of a user story

autoactivate on
autonumber

actor "TeamMember" as User #lightblue
participant "EffortUserStoryUI" as System
participant ":EffortUserStoryController" as Ctrl
participant ":UserStoryEffortService" as Service
participant ":UserStoryRepository" as Repo
participant "userStory: UserStory" as US
participant "effort: UsHour" as Effort

activate User

User -> System: Asks for a specific user story
System -> Ctrl: findByID(usNameDTO)
Ctrl -> Service: findByID(usNameDTO.getUserStoryID)
Service -> Repo: findByID(UserStoryID)
Repo --> Service: userStory
Service --> Ctrl: userStory
Ctrl --> System: userStory
System --> User: Show user story information
User -> System: Sets time effort
System -> Ctrl: createTimeEffort(effortDTO)
Ctrl -> Service: createTimeEffort(effortDTO.getEffort)
Service -> US: createTimeEffort(effort)
US -> Effort**: createTimeEffort(effort)
Effort -> Effort: validateEffort()
Effort --> US: true
US --> Service: true
Service --> Ctrl: true
Ctrl --> System: true
System --> User: Confirms time effort





@enduml