@startuml

hide circle
skinparam classAttributeIconSize 0

title Domain Model excerpt - "US027 - As Director, I want to define the Product Owner of a project."

class Company {
}

class ProjectTeam {
    }

class Resource {
    - startDate
    - endDate
    - costPerHour
    - percentageOfAllocation, startDateNewRole, role)
}

class ProjectRole {
    - name
}

class Project {
    - code
    - projectName
    - description
    - startDate
    - endDate
    - numberOfSprints
    - sprintDuration
}

class Sprint {
    - name
    - startDate
    - endDate
}

Company "1" -down-> "*" Project: contains
Project "1" -right- "1" ProjectTeam: belongs to
Sprint "*" -right- "1" Project: in divided into
Resource "*" -left-> "1" ProjectTeam: is associate
Resource "*" -down- "1" ProjectRole: plays a
Resource "1..*" -up- "*" Sprint: participates


@enduml