@startuml
'https://plantuml.com/class-diagram

title US028 - As Director, I want to get a list of all human resources in a project

class ProjectId <<Value Object>>
class SystemUserId <<Value Object>> #lightblue
class ResourceId <<Value Object>> #lightpink

package Project <<Rectangle>> {
    entity Project <<root>>
}

package SystemUser <<Rectangle>> {
    entity SystemUser <<root>> #lightblue
}

package Resource <<Rectangle>> {
    entity Resource <<root>> #lightpink
}

Project "1"-->"1" ProjectId
SystemUser "1"-->"1" SystemUserId
Resource "1"-->"1" ResourceId

ResourceId "1"-r>"1" SystemUserId
ResourceId "1"-l>"1" ProjectId

@enduml