@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US024 - As Administrator, I want to get a list all user accounts and their status

class UserAccountStatusUI {

}

class ProductBacklogSortController {
    +getProjectListByUserEmail(String email)
    +getProject(String code)
    +getUsSortedByPriority()
}

class Company {
    +getProjectStore()
}

class ProjectStore {
+getProjectListByUserEmail(String email)
+getProjectByCode(String code)
}

class Project {
-code : String
-productBacklog : ProductBacklog
+getProductBacklog()
}

class ProductBacklog {
-userStoryList : List<UserStory>
+getUsSortedByPriority()
}

class UserStory {
- userStoryStatus : UserStoryStatus
- priority : int
- description : String
- id_UserStory : int
- parentUserStory : UserStory
}

UserAccountStatusUI ..> ProductBacklogSortController

ProductBacklogSortController ..> Company
ProductBacklogSortController ..> ProjectStore
ProductBacklogSortController ..> Project
ProductBacklogSortController ..> ProductBacklog

Company "1" o-- "1" ProjectStore: has
ProjectStore "1" *-- "0..*" Project: has
Project "1" -> "1" ProductBacklog
ProductBacklog "1" -> "0..*" UserStory
@enduml