@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram US 028 "As Director, I want to get a list of all human resources in a project"

autoactivate on
autonumber

actor "Director" as actor
participant ":GetAllResourcesInProjectRoute" as route
participant ":GetAllResourcesInProjectController" as ctrl
participant ":GetAllResourcesInProjectService" as srv
participant ":IRepositoryProject" as projrepo
participant ":IRepositoryResource" as resrepo
participant "resources :List<Resource>" as resList
participant ":FilterResourcesByUsersService" as dsrv
participant "finalResources:List<Resource>" as resList2
participant "res :Resource" as res
participant ":ResourceId" as resId
participant ":ResourcesInProjectMapper" as map
participant "dataDto :DataDto" as dataDto
participant "resourcesDto :List<ResourceDto>" as dtoList
participant ":ResourceDto" as dto
participant "resourcesJson :List<ResourceJson>" as jsonList
participant ":ResourceJson" as json

activate actor
autoactivate on

actor -> route : GET /projects/{projectId}/resources
route -> ctrl : getAllResourcesInProject()
ctrl -> map: data2Dto(data)
map --> dataDto**: create()
note over map : The sequence of this method are hidden to simplify the diagram.
map --> ctrl: dataDto
ctrl -> srv : getAllResourcesInProject(dataDto)
srv -> projrepo: existById(dataDto.projectId) : true
deactivate
srv -> resrepo : findByProject(dataDto.projectId)
resrepo --> resList** : create()
note over resrepo : The sequence of this method are hidden to simplify the diagram.
resrepo --> srv : resources
srv -> dsrv : filterByUsers(resources)
dsrv --> resList2** : create()
note over dsrv : The sequence of this method are hidden to simplify the diagram.
dsrv --> srv : finalResources
srv -> map : model2Dto(finalResources)
map --> dtoList** : create()
note over map : The sequence of this method are hidden to simplify the diagram.
map --> srv : resourcesDto
srv --> ctrl : resourcesDto
ctrl -> map : dto2Json(resourcesDto)
map --> jsonList**
note over map : The sequence of this method are hidden to simplify the diagram.
map --> ctrl : resourcesJson
ctrl --> route : resourcesJson
route --> actor : Show all resources of the project


@enduml