@startuml
'https://plantuml.com/class-diagram

'hide circle
skinparam classAttributeIconSize 0

title US011 - As Authenticated User, i want to change his/her password


class ChangePasswordUI {
}

class ChangePasswordController {
+changePassword(email, oldPassword, newPassword, newPasswordConfirmation)
}

class Company {
+getSystemUserStore()
}

class SystemUserStore {
+getUserByEmail(email)
}

class SystemUser {
username : String
email : String
photo : String
password : String
passwordConfirmation : String
function : String
activateUser : boolean = False
+SystemUser(username, email, photo, password, passwordConfirmation, function, profile)
+isYourEmail(email)
+updatePassword(oldPassword, newPassword, newPasswordConfirmation)
-validateOldPassword(oldPasswordUI)
-setPassword(newPassword)
}

ChangePasswordUI ..> ChangePasswordController

ChangePasswordController ..> Company
ChangePasswordController ..> SystemUserStore
ChangePasswordController ..> SystemUser

Company "1" o-- "1" SystemUserStore: has
SystemUserStore "1" *-- "0..*" SystemUser: has

@enduml