@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

title US011 - "As Authenticated User, i want to change his/her password"


participant ": IUserRepository" as Repository
participant ": UserJpaAssembler" as Assembler
participant "userJpa:UserJpa" as USJPA
participant ":IUserRepositoryJpa" as Driver
participant "savedData:Data" as Data
participant "user:User" as US

[o->Repository: findByUserID (userID)

Repository -> Assembler : toData(user)
Assembler --> USJPA **: create ()
Assembler --> Repository : userJPA
Repository -> Driver: save(userJpa)
Driver --> Data**: create(savedUserJpa)
Driver --> Repository : savedData
Repository -> Assembler: toDomain (savedData)
Assembler -> US **: create()
Assembler --> Repository :user

[<--Repository: user

@enduml