@startuml

skinparam classAttributeIconSize 0

title US013 - "As Administrator, I want to create user profiles."

package "InfraEstructure" <<Rectangle>> #lightblue {
package "Route"{
    class "CreateUserProfiles" as route <<Component>>
    }

    package "Persistence" {
    class "IUserProfileRepositoryJpa" as jpa <<Interface>>
    }
}

package "Interface Adapter" <<Rectangle>> #lightgreen{
package "Controllers" <<Folder>>{
    class "UserProfileController" as ctrl <<Component>>{
    +createUserProfile(json)
    }
    }
    package "Repositories" <<Folder>>{
    class "UserProfileRepository" as uRepo <<Repository>>{
    +save(newUserProfile)
    +existsByDescription(description)
    }
}
}

package "DTO" <<Rectangle>>{
    class "UserProfileDTO" as dto <<Component>> {
    -userProfileName: String
    }

    class "UserProfileMapper" as mapper <<Component>> {
    +toDto(newUserProfile)
    }
}

package "Application Service"<<Rectangle>> #implementation {
    package "App Service" {
        class "UserProfileService" as service <<Service>>{
        +createAndSaveUserProfile(dto)
        }
    }
    package "Repositories Interface" {
        class "IUserProfileRepo" as iUserProfileRepo <<(I, Violet) Interface>> {
            +save(newUserProfile)
            +existsByDescription(description)
        }
    }
    package "User Profile Factory Interface" {
    class "IUserProfileFactory" as iUserProfileFactory <<(I, Violet) Interface>> {
            +createUserProfile(dto)
            }
    }
}

package "Domain" <<Rectangle>>#burlywood  {
    package "Factory" {
        class "UserProfileFactory" as userProfileFactory <<Factory>> {
        +createUserProfile(dto)
        }

        class "UserProfileIDFactory" as userProfileIDFactory <<Factory>> {
        +createUserProfileID(userProfileName)
        }
        class "IUserProfileIDFactory" as iUserProfileIDFactory <<(I, Violet) Interface>> {
        +createUserProfileID(userProfileName)
        }
    }

    package "Aggregate" {
        class "UserProfile" as userProfile <<Root>>{
            +UserProfile (userProfileID)
        }
    }
    package "Value Object"  {
        class "UserProfileID" as userProfileID <<Value Object>>{
        +UserProfileID (description)
        }
    }
}

    package "Data Model" <<Rectangle>>{
        class "UserProfileJpaAssembler" as assemblerjpa <<Component>> {
        +toData (userProfile)
        +toModel(userProfileJpa)
        }

        class "UserProfileJpa" as UPjpa {
        -userProfileID: UserProfileID
        }

route ..> ctrl
ctrl ..> service
uRepo ..|> iUserProfileRepo
service .left.> iUserProfileRepo
service ..|> iUserProfileFactory
service .down.> dto
service .down.> mapper
userProfileFactory ..|> iUserProfileFactory
userProfileIDFactory ..|> iUserProfileIDFactory
userProfileFactory ..> iUserProfileIDFactory
userProfileFactory ..> userProfile
userProfileFactory .down.> dto
userProfileIDFactory ..> userProfileID
uRepo ..> jpa
uRepo ...> assemblerjpa
uRepo ...> UPjpa





@enduml