@startuml
'https://plantuml.com/class-diagram

'hide circle
skinparam classAttributeIconSize 0

title US003 - As Visitor, I want to send a request to the administrator to assign him/her a given profile

skinparam classAttributeIconSize 0

'''''''''''''''''''''''''''''''
package "Infrastructure" <<Rectangle>> #lightblue  {
package "Route"{
    class "SendProfileRequestRoute" as route << Component >>
    }

package "Persistence" {
    interface "IUserProfileJPARepository" as iUserRepositoryJPA << Interface >>{
    + existsById(userProfileID)
    }
    }
}
'''''''''''''''''''''''''''''''
package "Interface Adapter" <<Rectangle>> #lightgreen {

  package "Controllers" <<Folder>>{
    class "UserProfileController" as ctrl << Component >> {
    +createAndAddRequest(requestDTO)
    }
  }
  package "Repositories" <<Folder>>{
    class "UserRepository" as UserRepo << Repository >> {
    + findUserByID(userID)
    + save(user)
    }
  }
  package "Repositories" <<Folder>>{
    class "UserProfileRepository" as UserProfileRepo << Repository >> {
    + existsByUserProfileId(userProfileID)
    }
  }
}

package "Application Service API/Use Case Service" <<Rectangle>> #lightpink{
  package "App Service" <<Folder>>{
    class "UserService" as service << Component >> {
    +createAndAddRequest(requestDTO)
    }
  }
  package "Repositories Interface" <<Folder>>{
    interface "IUserRepo" as iUserRepo << Interface >>{
    + findUserByID(userID)
    + save(user)
    }
  }
    package "Repositories Interface" <<Folder>>{
      interface "IUserProfileRepo" as iUserProfileRepo << Interface >>{
    + existsByUserProfileId(userProfileID)
      }
    }
}
'''''''''''''''''''''''''''''''
package "DTO" <<Rectangle>> {

  package "RequestDTO" <<Folder>>{
    class "RequestDTO" as outDto << Component >> {
    - profileID : String
    }
  }

}

package "Data Model" <<Rectangle>>{
package "Assembler" as generalAssembler {
    class "UserJPAAssembler" as assembler <<Component>>{
    +toDomain(foundUserJPA)
    }
    }
package "JPA" as generalJPA {
    class "UserJPA" as jpa {
    + create()
    }
    }
}
'''''''''''''''''''''''''''''''
package "Domain" <<Rectangle>> #burlywood{
  package "UserAggregate" as SUAggregate <<Folder>>{
    class "User" as user << Root >> {
    - userName : Name
    - photo : Photo
    - encryptedPassword : Description
    - function : Function
    - isActive : boolean
    - requestedProfiles : List<Request>
    + SystemUser(systemUserID)
    +createProfileRequest(profileID)
    }
  }

  package "Value Object" as valueObject <<Folder>>{
    class "UserID" as SUID << Value Object >> {
    -email : Email
    +SystemUserID(email)
    }

        class "Request" as request << Value Object >> {
        -date : LocalDate
        -id : UserProfileID
        +create(profileID)
        }

}


route ..> ctrl
ctrl .down.> service
service ..|> iUserRepo
iUserRepo ..> jpa
service ..> UserProfileRepo
UserProfileRepo ..> iUserRepositoryJPA
service ..> user
user ..> request
user ..> SUID
iUserRepo ..> assembler
assembler ..> user
assembler ..> jpa
service ..|> iUserProfileRepo
iUserRepo ..|> UserProfileRepo
service .down.> outDto
@enduml