@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US003 - As Visitor, I want to send a request to the administrator to assign him/her a given profile

skinparam classAttributeIconSize 0

'''''''''''''''''''''''''''''''
package "Infrastructure" <<Rectangle>> #lightblue  {
package "Route"{
    class "UserRoute" as route << Component >>
    }

package "Persistence" {
    interface "IUserJPARepository" as iUserRepositoryJPA << Interface >>
    }
}
'''''''''''''''''''''''''''''''
package "Interface Adapter" <<Rectangle>> #lightgreen {

  package "Controllers" <<Folder>>{
    class "UserController" as ctrl << Component >> {
    +createAndAddRequest(requestDTO)
    }
  }
  package "Repositories" <<Folder>>{
    class "UserRepository" as UserRepo << Repository >> {
    + findUserByID(userID)
    + update(opUser)
    }
  }
  package "Repositories" <<Folder>>{
    class "UserProfileRepository" as UserProfileRepo << Repository >> {
    + existsByUserProfileId(userProfileID)
    + update(opUser)
    }
  }
}

package "Application Service API/Use Case Service" <<Rectangle>> #lightpink{
  package "App Service" <<Folder>>{
    class "UserService" as service << Component >> {
    +createAndAddRequest(requestDTO)
    }
  }
  package "Repositories Interface" <<Folder>>{
    interface "IUserRepo" as iUserRepo << Interface >>{
    + findUserByID(userID)
    + update(opUser)
    }
  }
}
'''''''''''''''''''''''''''''''
package "DTO" <<Rectangle>> {
  package "IDDTO" <<Folder>>{
    class "idDTO" as idDto << Component >> {
    - id : String
    }
  }

  package "OutputUserDTO" <<Folder>>{
    class "OutputUserDTO" as outDto << Component >> {
    - userName : String
    - email : String
    - function : String
    - photo : String
    - isActive : String
    - assignedIDProfiles : String []
    }
  }

  package "UserMapper" <<Folder>>{
    class "UserMapper" as mapper << Component >> {
    + toDto(savedUser)
    }
  }
}

package "Data Model" <<Rectangle>>{
package "Assembler" as generalAssember {
    class "UserJPAAssembler" as assembler <<Component>>{
    +toDomain(foundUserJPA)
    }
    }
package "JPA" as generalJPA {
    class "UserJPA" as jpa {
    }
    }
}
'''''''''''''''''''''''''''''''
package "Domain" <<Rectangle>> #burlywood{
  package "UserAggregate" as SUAggregate <<Folder>>{
    class "User" as user << Root >> {
    - userName : Name
    - photo : Photo
    - encryptedPassword : Description
    - function : Function
    - isActive : boolean
    - requestedProfiles : List<Request>
    + SystemUser(systemUserID)
    }
  }

  package "Value Object" as valueObject <<Folder>>{
    class "UserID" as SUID << Value Object >> {
    -email : Email
    +SystemUserID(email)
    }

}

@enduml