@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
'hide circle

title US031 - As Team Member, I want to create a task in a user story


package System <<Rectangle>>{

package Infrastructure <<Rectangle>> #lightblue {
class "CreateUsTaskRoute" as route<<Component>>{
}
}

package InterfaceAdapters <<Rectangle>> #lightgreen{
class "CreateUsTaskController" as ctrl <<Component>>{
+createUsTask(CreateTaskDTO dto)
}

class "TaskStore" as store <<Repository>>{
-taskList: List<Task>
+saveTask(Task task)
-validate()
-add()
}
}

package ApplicationService <<Rectangle>> #lightpink{
interface "ITaskStore" as istore {
+saveTask(Task task)
}

class "CreateUsTaskService" as service <<Service>>{
+createUsTask(taskDto)
}
}

package Domain <<Rectangle>> #burlywood{

package Aggregates <<Rectangle>>{

package Task <<Rectangle>>{

entity "Task" as task <<root>>{
-int idTask
-Name name
-Description description
-TaskTypeEnum type
-double effortEstimate
-LocalDate startDate
-LocalDate endDate
-Resource responsible
-List<Task> tasksPrecedence
-List<Effort> taskEffortList
+Task(String name,String description,int effort,\nTaskType type,List<Task> precedence,Resource responsible)
}

}
}
package ValueObjects <<Rectangle>>{
class taskId{
}
}
}

package DTO <<Rectangle>> #lightgray {

class "TaskMapper" as mapper <<Component>>{
+toModel(CreateTaskDTO dto)
+toDTO(Task task)
}

class CreateTaskDTO <<Component>>{
-String name
-String description
-int effortEstimate
-String taskTypeName
-String responsibleEmail
+CreateTaskDTO(Task task)
+getName()
+getDescription()
+getEffortEstimate()
+getTaskTypeName()
+getResponsible()
}

class DataDto <<Component>> {
+toModel(CreateTaskDTO dto)
+toDTO(Task task)
}
}
}

route .d.> ctrl

ctrl .d.> service
ctrl .d.> mapper


mapper ..> task




@enduml