@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title As Project Member, I want to update the status (i.e.: the Scrum Board category) of a user story in the scope of the current sprint backlog.

class UpdateStatusUSSprintUI {
}

class UpdateStatusUSSprintController {
    +getSprint(code): Sprint
}

class Company {
    +getProjectStore()
}

class ProjectStore {
    +getProjectByCode(code)
}

class Project {
    +getSprintBacklog()
}

class SprintBacklog {
    +getUserStoryList()
}

class SprintListMapper {
    +toDTO(usList)
    +getUS()
    +create()
    +add(usDTO)
}

class Userstory {
    +setStatus(userStoryStatus)
}

class usDTO {

}



UpdateStatusUSSprintUI ..> UpdateStatusUSSprintController

UpdateStatusUSSprintController ..> Company

UpdateStatusUSSprintController ..> ProjectStore

UpdateStatusUSSprintController ..> Project

UpdateStatusUSSprintController ..> SprintBacklog

UpdateStatusUSSprintController ..> SprintListMapper

UpdateStatusUSSprintController ..> Userstory

Company "1" -> "1" ProjectStore: knows

ProjectStore "1" -> "0..*" Project: contains

Project "1" -> "1" SprintBacklog: contains

SprintBacklog "1" -> "0..*" Userstory: contains

SprintListMapper"1" -> "0..*" usDTO: contains

@enduml