@startuml
'https://plantuml.com/sequence-diagram

title Example of a System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":System" as System

activate User

User -> System: Authentication Request
System --> User: Authentication Response

User -> System: Another authentication Request
User <-- System: another authentication Response
@enduml