@startuml
'https://plantuml.com/sequence-diagram

title As Product Owner I want to change the Priority of a user story in the backlog

autoactivate on
autonumber

actor "Product Owner" as PO
participant ":ChangePriorityUI" as System
participant ":ChangePriorityController" as Ctrl
participant ": Company" as C1
participant "projStore : ProjectStore" as C2
participant "projectList : List<Project>" as C2.1
participant "proj : Project" as C3
participant "prodBack : ProductBacklog" as C4
participant "us : UserStory" as C5

activate PO



PO -> System: Get list of projects associated to user
System -> Ctrl: getCurrentProjectListByUserEmail(email)
Ctrl -> C1: getProjectStore()
C1 --> Ctrl: projStore
Ctrl --> C2: getCurrentProjectListByUserEmail(email)
C2 -> C2.1 ** : createProjectList
 loop
C2 -> C2.1: addProjectToList
C2.1 --> C2: true
end
C2 --> Ctrl: projectList
Ctrl --> System: projectList
System --> PO: Shows projectList
PO -> System: Picks project
System -> Ctrl: getProjectByCode(code)
Ctrl -> C2: getProjectByCode(code)
C2 --> Ctrl: proj
Ctrl --> System: proj
System --> PO: Shows project information
PO -> System: Access product backlog
System -> Ctrl: getUserStoryList()
Ctrl -> C3: getUserStoryStore
C3 --> Ctrl: prodBack
Ctrl -> C4: getUserStoryList()
C4 --> Ctrl: usList
Ctrl --> System: usList
System --> PO: Shows US List
PO -> System: Picks User Story
System -> Ctrl: getUserStory(id)
Ctrl -> C4: getUserStory(id)
C4 --> Ctrl: us
Ctrl --> System: us
System --> PO: Shows US Information
PO -> System: Set Priority
System -> Ctrl: setPriority(priority)
Ctrl -> C5: setPriority(priority)
C5 -> C5: validatePriority(priority)
C5 --> Ctrl: true
Ctrl --> System: true
System --> PO: Confirms success



@enduml