@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle

title Excerpt Domain Model of US001 - As Non-Registered User, I want to register as an application user

together {
class Company{
}
'class Resource{
'- startDate
'- endDate
'- costPerHour
'- percentageOfAllocation
'}
'class ProjectRole{
'- name
'}
class UserProfile{
- name
}
class Request{
- requestDate
- requestStatus
}
class SystemUser{
- userName
- email
- photo
- password
- function
- activateUser
}
}

SystemUser "1" -- "*" Request: sent by
'SystemUser "1" -- "*" Resource: act as
Company "1" -left- "*" SystemUser: employed by
UserProfile "1..*" -- "*" SystemUser: is assigned
Request "*" <-- "1" UserProfile: asks for a
'Resource "*" -left- "1" ProjectRole: plays a
'Resource "*" -left-> "1" ProjectTeam: is associate
@enduml