@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram of US001 - As Non-Registered User, I want to register as an application user

autoactivate on
autonumber

actor "Non-Registered User" as User
participant ":RegisterUserUI" as UI
participant ":RegisterUserController" as Ctrl
participant ":Company" as Company
participant "profileStore:UserProfileStore" as UserProfileStore
participant "visitorProfile:UserProfile" as UserProfile
participant "usersStore:SystemUserStore" as SystemUserStore
participant "user:SystemUser" as SystemUser

activate User

User -> UI: Ask to register new user
UI --> User: request data (userName, email, function, password, passwordConfirmation, photo)
User -> UI: Types request data
UI -> Ctrl: createSystemUser(UserName, email, function, password, passwordConfirmation, photo)
Ctrl -> Company: getUserProfileStore()
Company --> Ctrl: profileStore
Ctrl -> UserProfileStore: getProfileByName(visitor)
loop for each profile in UserProfileStore
UserProfileStore -> UserProfile: isYourProfile(visitor)
UserProfile --> UserProfileStore: true
end
UserProfileStore --> Ctrl: visitorProfile
Ctrl -> Company: getSystemUserStore()
Company --> Ctrl: usersStore
Ctrl -> SystemUserStore: createSystemUser(userName, email, function, password, passwordConfirmation, photo, visitorProfile?)
SystemUserStore --> SystemUser**: create()
SystemUserStore --> Ctrl: user
Ctrl -> SystemUserStore: saveSystemUser(user)
SystemUserStore -> SystemUserStore: validateSystem(user)
deactivate SystemUserStore
SystemUserStore -> SystemUserStore: addSystem(user)
deactivate SystemUserStore
SystemUserStore --> Ctrl: true
Ctrl --> UI: true
UI --> User: informs operation success

'System -> Ctrl: authenticate(userId, pwd)
'Ctrl -> C1: doLogIn(userId, pwd)
'C1 --> Ctrl: userToken
'Ctrl --> System: ok
'System --> User: Authentication Response

@enduml