@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title US022 - As Project Manager, i want to create a sprint.

class CreateSprintUI {
}

class CreateSprintController {
+getUser(email)
+updateSystemUser(username, function, photo)
}

class Company {
+getSystemUserStore()
}

class SystemUserStore {
+getUserByEmail(email)
}


class SystemUser {
username : String
email : String
photo : String
password : String
passwordConfirmation : String
function : String
activateUser : boolean = False
+SystemUser(username, email, photo, password, passwordConfirmation, function, profile)
+isYourEmail(email)
+setAllData(username, function, photo)
+setUsername(username)
+setFunction(function)
+setPhoto(photo)
}


class SystemUserMapper {
+toUserDTO(user)
-toDTO(user)
+create()
}


CreateSprintUI ..> CreateSprintController

CreateSprintController ..> Company
CreateSprintController ..> SystemUserStore
CreateSprintController ..> SystemUser
CreateSprintController ..> SystemUserMapper


Company "1" o-- "1" SystemUserStore: has
SystemUserStore "1" *-- "0..*" SystemUser: has


@enduml