@startuml
'https://plantuml.com/sequence-diagram

title US022 - As Project Manager, I want to create a sprint.

autoactivate on
autonumber

actor "Project Manager" as ProjectManager
participant ":System" as System

activate ProjectManager

ProjectManager -> System: Starts to create a Sprint
'System -> System: createSprint
'deactivate
System --> ProjectManager: Informs Operation Success

@enduml