@startuml
'https://plantuml.com/sequence-diagram

title US009 - As Product Owner, I want to create a user story and add it to the Product Backlog

autoactivate on
autonumber


participant ": CreateUserStoryRoute" as System
participant ": CreateUserStoryController" as Ctrl
participant ": CreateUserStoryService" as appService
participant ": UserStoryDto" as usDto
participant ": IUserStoryFactory" as factory
participant "newUserStory : \n UserStory" as us
participant ": IRepoUserStory " as usStore
participant ": UserStoryMapper" as usMapper
participant "outputUsDto : OutputUsDto" as outDto



[o-> System: POST/userStories(json)
System -> Ctrl: createUserStory(json)
note right
Change from json to dto hidden to simplify diagram
end note
Ctrl -> appService: createAndSaveUserStory(dto)
appService -> usDto: projectID = getProjectID()
deactivate
appService -> usDto: userStoryID = getUserStoryID()
deactivate
appService -> usDto: title = getTitle()
deactivate
appService -> usDto: priority = getPriority()
deactivate
appService -> usDto: description = getDescription()
deactivate
appService -> usDto: timeEstimate = getTimeEstimate()
deactivate
appService -> factory:  createUserStory(projectID, userStoryID, title,\n priority, description, timeEstimate)
factory -> us **: create()
factory --> appService: newUserStory

appService-> usStore: save(newUserStory)
usStore-> usStore: existsByUserStoryId\n(UserStoryID)
deactivate
usStore-> usStore: add(newUserStory)
deactivate
usStore --> appService : true
appService-> usMapper : toDto(newUserStory)
usMapper-> outDto **:create()
usMapper --> appService: outputUsDto
appService --> Ctrl: outputUsDto
Ctrl --> System: outputUsJson
note right
Change from json to dto hidden to simplify diagram
end note
[<--System : Informs that user story was created

@enduml

