@startuml
'https://plantuml.com/sequence-diagram

title US009 - As Product Owner, I want to create a user story and add it to the Product Backlog

autoactivate on
autonumber

actor "Product Owner" as User #lightgreen
participant ": CreateUserStoryRoute" as System
participant ": CreateUserStoryController" as Ctrl
participant ": CreateUserStoryService" as appService
participant " dto : UserStoryDto" as usDto
participant ": UserStoryFactory" as factory
participant "us : UserStory" as us
participant ": UserStoryStore " as usStore
participant ": UserStoryMapper" as usMapper
participant "outputUsDto : OutputDto" as outDto
participant "outputUsJson : UserStoryJson" as outJson


activate User


User -> System: Start to create a user story
System --> User : Requests information: \n  (projectID, userStoryID, title, \n  priority, description, timeEstimate)
User -> System: Enter requested information
System -> Ctrl: createUserStory(userStoryDto)
Ctrl -> appService: createAndSaveUserStory(userStoryDto)
appService -> factory:  createUserStory(dto.getProjectID, dto.getUserStoryID, dto.getTitle,\n dto.getPriority, dto.getDescription, dto.getTimeEstimate)
factory -> us **: create()
factory --> appService: us
appService -> appService: save(us)

appService-> usStore: save(us)
usStore-> usStore: existsByUserStoryId(us.getUserStoryId())
deactivate
usStore-> usStore: add(us)
deactivate
usStore --> appService : true
deactivate
appService-> usMapper : toDto(us)
usMapper-> outDto **:create()
outDto-->usMapper: outputUsDto
usMapper --> appService: outputUsDto
appService -> usMapper: dtoToJson(outputUsDto)
usMapper-> outJson **:create()
outJson-->usMapper: outputUsJson
usMapper --> appService: outputUsJson
appService --> Ctrl: outputUsJson
Ctrl-->System: outputUsJson
System--> User: Informs that user story was created

@enduml

