@startuml
'https://plantuml.com/sequence-diagram

title US009 - As Product Owner, I want to create a user story and add it to the Product Backlog

autoactivate on
autonumber

actor "Product Owner" as User
participant ": CreateUserStoryUI" as System
participant ": CreateUserStoryController" as Ctrl
participant ": Company" as C1
participant ": ProjectsMapper" as C2.1.0
participant " projStore : ProjectStore" as C2
participant "projectListByUser : List <Project>" as C2.1
participant "projectListByUserDtoList : List <ProjectDTO>" as C5
participant "projectListByUserDto : ProjectDTO" as C6
participant "proj : Project" as C3
participant ": ProductBacklogMapper" as prodbackM
participant ": ProductBacklog" as C4
participant ": UserStoryMapper" as usMapper
participant "createUserStoryDto : CreateUserStoryDto" as usdto
participant "us : UserStory" as C5.1

activate User


User -> System: Get list of project where is associated
System -> Ctrl: getProjectListByUserEmail(email)
Ctrl -> C1: getProjectStore()
C1 --> Ctrl: projStore
Ctrl -> C2: getProjectListByUserEmail(email)
C2 -> C2.1 ** : createProjectList

loop for each known project in projectList has email
C2->C2.1 : addProjectList
C2.1-->C2 : true
end

C2 --> Ctrl: projectListByUser
Ctrl-> C2.1.0: toDtoByUser(projectListByUser)
C2.1.0->C5 ** : create()

loop for each known project in projectList
C2.1.0->C2.1: code = getCode()
deactivate C2.1
C2.1.0->C2.1: projectName = getprojectName()
deactivate C2.1
C2.1.0->C2.1: description = getDescription()
deactivate C2.1
C2.1.0->C6 ** : create (code, projectName, description)
C2.1.0->C5: add(projectListByUserDto)
C5-->C2.1.0: true
end

C2.1.0 --> Ctrl: projectListByUserDtoList
Ctrl --> System: projectListByUserDtoList
System --> User : Shows projectList to select project

User -> System: Choose project and starting creating a us (code,status,priority,description)
System -> Ctrl: createUserStory(code, createUserStoryDto)
Ctrl -> C2 : getProjectByCode(code)
C2 --> Ctrl : proj
Ctrl-> C3 : getProductBacklog()
C3 --> Ctrl : productBacklog
Ctrl -> C4 : createUserStory(createUserStoryDto)
C4-> usMapper: toModel(createUserStoryDto)
usMapper -> usdto : name = getName()
deactivate usdto
usMapper -> usdto : status = getStatus()
deactivate usdto
usMapper -> usdto : priority = getPriority()
deactivate usdto
usMapper -> usdto : description = getDescription()
deactivate usdto
usMapper->C5.1 : isValidUserStory(name, status, priority, description)
usMapper -> C5.1 ** : create(name, status, priority, description)

usMapper-->C4 : us
C4-->Ctrl : us
Ctrl->C4 : saveUserStory(us)
C4->C4 : validateUserStory(us)
C4->C4 : addUserStory(us)
C4-->Ctrl : true
Ctrl --> System : true
System --> User : Shows us data created

@enduml

