@startuml
'https://plantuml.com/sequence-diagram

title US009 - As Product Owner, I want to create a user story and add it to the Product Backlog

autoactivate on
autonumber


participant ": CreateUserStoryRoute" as System
participant ": CreateUserStoryController" as Ctrl
participant ": CreateUserStoryService" as appService
participant ": IUserStoryFactory" as factory
participant ": UserStoryDto" as usDto
participant "newUserStory : \n UserStory" as us
participant ": IRepoUserStory " as usStore
participant ": UserStoryMapper" as usMapper
participant "outputUsDto : \n UserStoryDto" as outDto



[o-> System: POST/userStories(json)
System -> Ctrl: createUserStory(json)
note right
Change from json to dto hidden to simplify diagram
end note
Ctrl -> appService: createAndSaveUserStory(userStoryDTO)
appService -> factory:  createUserStory(userStoryDTO)
factory -> usDto: projectID = getProjectID()
deactivate
factory -> usDto: userStoryID = getUserStoryID()
deactivate
factory -> usDto: title = getTitle()
deactivate

factory -> us **: create()
factory --> appService: newUserStory

appService-> usStore: save(newUserStory)
usStore-> usStore: existsByUserStoryId\n(UserStoryID)
deactivate
usStore-> usStore: add(newUserStory)
deactivate
usStore --> appService : true
appService-> usMapper : toDto(newUserStory)
usMapper-> outDto **:create()
usMapper --> appService: outputUsDto
appService --> Ctrl: outputUsDto
Ctrl --> System: outputUsJson
note right
Change from json to dto hidden to simplify diagram
end note
[<--System : Informs that user story was created

@enduml

