@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram US 028 "As Director, I want to get a list of all human resources in a project"

autoactivate on
autonumber

actor "Director" as Director
participant ":GetListHResourceProjectUI" as UI
participant ":GetListHResourceProjectController" as Controller
'participant ":Company" as Company
participant "ResourceRepository" as ResRepository
'participant "projectTeam:List<Resource>" as ProjectTeam2
'participant "proj:Project" as Project
'participant "projTeam:ProjectTeam" as ProjectTeam
participant "ProjectTeamMapper" as ProjectTeamMapper
participant "projectTeam:List<Resource>" as ProjectTeam2
participant "res:Resource" as Resource
participant "projectTeamListDTO:List<ResourcesDTO>" as ProjectTeamDTO
participant "resDTO:ResourceDTO" as ResourceDTO

activate Director

Director -> UI: Ask to access project team of a project
UI -> Controller: getProjectTeam(projectCode)
'Controller -> Company: getProjectStore()
'Company --> Controller: projSt
Controller -> ResRepository: getProjectTeam(projectCode)
ResRepository --> ProjectTeam2**: create()
ResRepository -> Resource: hasProjectCode(projectCode)
Resource --> ResRepository: true
ResRepository -> ProjectTeam2: add(res)
ProjectTeam2 --> ResRepository: true
ResRepository --> Controller: projectTeam
'Controller -> ResRepository: getProjectTeam()
'Project --> Controller: projTeam
'Controller -> ProjectTeam: get ProjectTeamList()
'ProjectTeam --> Controller: projTeamList
Controller -> ProjectTeamMapper : toDTO(projectTeam)
ProjectTeamMapper --> ProjectTeamDTO**: create()
loop for each resource in projectTeam
ProjectTeamMapper -> ProjectTeam2: get(i)
ProjectTeam2 --> ProjectTeamMapper: res
ProjectTeamMapper -> Resource: getName()
Resource --> ProjectTeamMapper: name
ProjectTeamMapper -> Resource: getEmail()
Resource --> ProjectTeamMapper: email
ProjectTeamMapper -> Resource: getStartDate()
Resource --> ProjectTeamMapper: startdate
ProjectTeamMapper -> Resource: getEndDate()
Resource --> ProjectTeamMapper: enddate
ProjectTeamMapper -> Resource: getRole()
Resource --> ProjectTeamMapper: role
ProjectTeamMapper -> Resource: getCostPerHour()
Resource --> ProjectTeamMapper: costPerHour
ProjectTeamMapper -> Resource: getPercentageOfAllocation()
Resource --> ProjectTeamMapper: percentageOfAllocation
ProjectTeamMapper -> ProjectTeamMapper: resDTO = toDTO(res)
ProjectTeamMapper --> ResourceDTO**: create()
deactivate ProjectTeamMapper
ProjectTeamMapper -> ProjectTeamDTO: add(resDTO)
ProjectTeamDTO --> ProjectTeamMapper: true
end
ProjectTeamMapper --> Controller: projTeamListDTO
Controller --> UI: projTeamListDTO
UI --> Director: projTeamListDTO

@enduml