
@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide circle

title Domain Model
package Model {


package Project {
class Project <root>{
}
}


package Sprint {
class Sprint <root>{
}
}


package UserStory {
class UserStory <root>{
}
}


package Task {
class Task <root>{
}
}


package SystemUser {
class SystemUser <root>{
}
class Request{
}
}


package Typology {
class Typology <root>{
}
}


package UserProfile {
class UserProfile <<root>>{
}
}


package Resource{
class Resource <root>{
}
}


package Value-Object {
'class Description <VO>{
'}
class Email <VO>{
}
'class Name <VO>{
'}
'class CostPerHour <VO>{
'}
'class PercentageOfAllocation <VO>{
'}
'class ProjectRole <VO>{
'}
'class Photo <VO>{
'}
'class Function <VO>{
'}
'class Password <VO>{
'}
'class TaskEffort <VO>{
'}
'class Effort_Hour <VO>{
'}
'class Effort_Date <VO>{
'}
'class Comment <VO>{
'}
'class Attachment <VO>{
'}
'class Effort_Minutes <VO>{
'}
'class TaskStatus <VO>{
'}
'class TaskType <VO>{
'}
'class Title_UserStory <VO>{
'}
'class UserStoryStatus <VO>{
'}
'class BusinessSector <VO>{
'}
'class Customer <VO>{
'}
class ProjectCode <VO>{
}
'class Budget <VO>{
'}
'class SprintDuration <VO>{
'}
'class NumberOfSprints <VO>{
'}
'class ProjectStatus <VO>{
'}
class IdUserStory <VO>{
}
class IdSprint <VO>{
}
class IdUserProfile<VO>{
}
class IdTypology<VO>{
}
class IdTask<VO>{
}
'}
'}

SystemUser "1" --> "1" Email
Request "1" --> "1" IdUserProfile
UserProfile "1" --> "1" IdUserProfile
SystemUser "1" --> "1..*"IdUserProfile
Resource "*" --> "1" Email
Resource "*" --> "1" ProjectCode
Sprint "*" --> "1" ProjectCode
Project "1" --> "1" ProjectCode
UserStory "*" --> "1" ProjectCode
Project "1" --> "1" IdTypology
Typology "1" --> "1" IdTypology
Sprint "1" --> "1" IdSprint
UserStory "*" --> "0..1" IdSprint
UserStory "*" --> "1" IdUserStory
Task "*" --> "0..1" IdSprint
Task "*" --> "0..1" IdUserStory
Task "*" --> "1" IdTask



@enduml

