US13-MD.puml@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model extract - US013 - As Administrator, I want to create user profiles

class Company {
}

class SystemUser{
      - userName
      - email
      - photo
      - password
      - function
      - activateUser
      }

class UserProfile {
    - name
}

SystemUser "*" -> "1..*" UserProfile: knows
SystemUser "*" -> "1" Company: Employed

@enduml