@startuml
'https://plantuml.com/sequence-diagram

title US015 - As Director, I want to get a list of all projects

autoactivate on
autonumber

actor "Director" as User
participant ":System" as System

activate User

User -> System: wants to get a list of all projects

System-->User: return the list of all projects

@enduml