@startuml
'https://plantuml.com/class-diagram


'Layout Format---------------------------------------------
left to right direction
hide circle
skinparam classAttributeIconSize 0


title Domain Model


class SystemUser #Yellow{
-userName
-photo
-encryptedPassword
-function
-isActive
}

@enduml